name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
        
    - name: Install dependencies
      run: pnpm install
      
    - name: Build and package extension
      run: pnpm zip
      
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "output/*.zip"
        generateReleaseNotes: true
        token: ${{ secrets.GITHUB_TOKEN }}